### PR TITLE
fix: add update on approve

### LINKED ISSUE #221: bug: missing `epochOustandingInvest` & `epochOustandingRedeem` updates
The logic within `brm.ApproveDeposit` and `brm.ApproveRedeem` is missing logic to update the oustanding per epoch amounts. 

* Missing in invest deposits [here](https://github.com/centrifuge/api-v3/blob/044db992671863716acdea216f54aa705158003d/src/handlers/batchRequestManagerHandlers.ts#L294-L398)
* Missing in redeem deposits [here](https://github.com/centrifuge/api-v3/blob/044db992671863716acdea216f54aa705158003d/src/handlers/batchRequestManagerHandlers.ts#L191-L291)

The logic MUST reduce by the approved amounts respectively. 

## Additional request
Can we add the total queued amount to the epoch level too? I.e. 

* Adapt by the delta between `oldQueuedAmount` and `newQueuedAmount` 
  * Increase IF `new > old`
  * Decrease IF `old > new`

### PR DESCRIPTION
**Pull request by mustermeiszer**
fixes #221 

## Todo
* [x] Fix epoch
* [x] Add queued amounts

### CODE REVIEW

File: src/handlers/batchRequestManagerHandlers.ts [hunk 1]
```diff
@@ -101,8 +102,11 @@ export async function updateDepositRequest({
     },
     event
   )) as EpochOutstandingInvestService;
-
-  await epochOutstandingInvest.updatePendingAmount(pendingTotalAssetAmount).save(event);
+  const deltaQueuedAssetsAmount = queuedUserAssetAmount - (lastQueuedAssetsAmount ?? 0n);
+  await epochOutstandingInvest
+    .updatePendingAmount(pendingTotalAssetAmount)
+    .increaseQueuedAmount(deltaQueuedAssetsAmount)
```
Comment (filo87) [inline src/handlers/batchRequestManagerHandlers.ts]: @mustermeiszer is this what you had in mind for the queued amounts?
